# Generated by ariadne-codegen
# Source: ./src/binaryai/query.graphql

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class CompressedFile(BaseModel):
    file: Optional["CompressedFileFile"]


class CompressedFileFile(BaseModel):
    decompressed: Optional[
        List[
            Annotated[
                Union[
                    "CompressedFileFileDecompressedCompressedFile",
                    "CompressedFileFileDecompressedCompressedDirectory",
                ],
                Field(discriminator="typename__"),
            ]
        ]
    ]


class CompressedFileFileDecompressedCompressedFile(BaseModel):
    typename__: Literal["CompressedFile"] = Field(alias="__typename")
    path: str
    sha_256: str = Field(alias="sha256")


class CompressedFileFileDecompressedCompressedDirectory(BaseModel):
    typename__: Literal["CompressedDirectory"] = Field(alias="__typename")


CompressedFile.model_rebuild()
CompressedFileFile.model_rebuild()
