# Generated by ariadne-codegen on 2023-09-18 11:53
# Source: ./src/binaryai/query.graphql

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class CompressedFile(BaseModel):
    file: Optional["CompressedFileFile"]


class CompressedFileFile(BaseModel):
    decompressed: Optional[
        List[
            Annotated[
                Union[
                    "CompressedFileFileDecompressedCompressedDirectory",
                    "CompressedFileFileDecompressedCompressedFile",
                ],
                Field(discriminator="typename__"),
            ]
        ]
    ]


class CompressedFileFileDecompressedCompressedDirectory(BaseModel):
    typename__: Literal["CompressedDirectory"] = Field(alias="__typename")


class CompressedFileFileDecompressedCompressedFile(BaseModel):
    typename__: Literal["CompressedFile"] = Field(alias="__typename")
    path: str
    sha256: str


CompressedFile.model_rebuild()
CompressedFileFile.model_rebuild()
CompressedFileFileDecompressedCompressedDirectory.model_rebuild()
CompressedFileFileDecompressedCompressedFile.model_rebuild()
