# Generated by ariadne-codegen on 2023-09-18 11:53
# Source: ./src/binaryai/query.graphql

from typing import Any, List

from pydantic import Field

from .base_model import BaseModel


class CreateFile(BaseModel):
    create_file: "CreateFileCreateFile" = Field(alias="createFile")


class CreateFileCreateFile(BaseModel):
    sha256: str
    md5: str
    name: List[str]
    size: int
    mime_type: str = Field(alias="mimeType")
    create_time: Any = Field(alias="createTime")


CreateFile.model_rebuild()
CreateFileCreateFile.model_rebuild()
