# Generated by ariadne-codegen
# Source: ./src/binaryai/query.graphql

from typing import List, Optional

from .base_model import BaseModel


class CVEName(BaseModel):
    file: Optional["CVENameFile"]


class CVENameFile(BaseModel):
    scainfo: Optional[List["CVENameFileScainfo"]]


class CVENameFileScainfo(BaseModel):
    cves: Optional[List["CVENameFileScainfoCves"]]


class CVENameFileScainfoCves(BaseModel):
    name: str


CVEName.model_rebuild()
CVENameFile.model_rebuild()
CVENameFileScainfo.model_rebuild()
