# Generated by ariadne-codegen
# Source: https://api.binaryai.cn/v1/endpoint

from enum import Enum


class AnalyzeProgressStep(str, Enum):
    Begin = "Begin"
    Done = "Done"
    AutoAnalysis = "AutoAnalysis"
    Decompile = "Decompile"
    FeatureForward = "FeatureForward"
    EmbedRecall = "EmbedRecall"
    EmbedRank = "EmbedRank"
    ResultUpload = "ResultUpload"


class AntivirusSafeLevel(str, Enum):
    UNKNOWN = "UNKNOWN"
    SAFE_FORCE = "SAFE_FORCE"
    SAFE = "SAFE"
    SAFE_WEAK = "SAFE_WEAK"
    UNDETECTED = "UNDETECTED"
    MALICIOUS_WEAK = "MALICIOUS_WEAK"
    MALICIOUS = "MALICIOUS"
    MALICIOUS_FORCE = "MALICIOUS_FORCE"
    INFECTED = "INFECTED"


class ExecuteType(str, Enum):
    SmartBinary = "SmartBinary"
    SmartExtractor = "SmartExtractor"
    FileMeta = "FileMeta"
    SmartBeat = "SmartBeat"


class FileType(str, Enum):
    ELF = "ELF"
    PE = "PE"
    Macho = "Macho"
    COFF = "COFF"


class MalwareFamilyTag(str, Enum):
    TROJAN = "TROJAN"
    VIRUS = "VIRUS"
    WORM = "WORM"
    DOWNLOADER = "DOWNLOADER"
    C2 = "C2"
    RANSOM = "RANSOM"
    COINMINER = "COINMINER"
    ADWARE = "ADWARE"
    BOTNET = "BOTNET"


class MatchAlgorithm(str, Enum):
    Normal = "Normal"
    Professional = "Professional"


class NoopReason(str, Enum):
    AlreadyRunning = "AlreadyRunning"
    WouldNotChange = "WouldNotChange"
    RateLimited = "RateLimited"


class PseudoCodeAnnotationType(str, Enum):
    HAS_FUNC_DEF = "HAS_FUNC_DEF"
    HAS_XREF = "HAS_XREF"


class RelroLevel(str, Enum):
    No = "No"
    Full = "Full"
    Partial = "Partial"


class SCAAlgo(str, Enum):
    NORMAL = "NORMAL"
    PROFESSIONAL = "PROFESSIONAL"


class SearchBinaryStatisticKey(str, Enum):
    THIRD_LIB_NAME = "THIRD_LIB_NAME"
    THIRD_LIB_VERSION = "THIRD_LIB_VERSION"
    THIRD_LIB_CVE_NAME = "THIRD_LIB_CVE_NAME"


class Status(str, Enum):
    Ready = "Ready"
    Waiting = "Waiting"
    Running = "Running"
    Success = "Success"
    Fail = "Fail"
    Timeout = "Timeout"


class SymbolType(str, Enum):
    FUNCTION = "FUNCTION"
    THUNK_FUNCTION = "THUNK_FUNCTION"
    DATA_LABEL = "DATA_LABEL"


class XRefType(str, Enum):
    CALL = "CALL"
    DATA = "DATA"
    STRING = "STRING"
