# Generated by ariadne-codegen on 2023-09-18 11:53
# Source: https://api.binaryai.cn/v1/endpoint

from enum import Enum


class AntivirusSafeLevel(str, Enum):
    INFECTED = "INFECTED"
    MALICIOUS = "MALICIOUS"
    MALICIOUS_FORCE = "MALICIOUS_FORCE"
    MALICIOUS_WEAK = "MALICIOUS_WEAK"
    SAFE = "SAFE"
    SAFE_FORCE = "SAFE_FORCE"
    SAFE_WEAK = "SAFE_WEAK"
    UNDETECTED = "UNDETECTED"
    UNKNOWN = "UNKNOWN"


class ExecuteType(str, Enum):
    FileMeta = "FileMeta"
    SmartBeat = "SmartBeat"
    SmartBinary = "SmartBinary"
    SmartExtractor = "SmartExtractor"


class FileType(str, Enum):
    COFF = "COFF"
    ELF = "ELF"
    Macho = "Macho"
    PE = "PE"


class MatchAlgorithm(str, Enum):
    Normal = "Normal"
    Professional = "Professional"


class NoopReason(str, Enum):
    AlreadyRunning = "AlreadyRunning"
    RateLimited = "RateLimited"
    WouldNotChange = "WouldNotChange"


class PseudoCodeAnnotationType(str, Enum):
    HAS_FUNC_DEF = "HAS_FUNC_DEF"
    HAS_XREF = "HAS_XREF"


class RelroLevel(str, Enum):
    Full = "Full"
    No = "No"
    Partial = "Partial"


class SCAAlgo(str, Enum):
    NORMAL = "NORMAL"
    PROFESSIONAL = "PROFESSIONAL"


class SearchBinaryStatisticKey(str, Enum):
    THIRD_LIB_CVE_NAME = "THIRD_LIB_CVE_NAME"
    THIRD_LIB_NAME = "THIRD_LIB_NAME"
    THIRD_LIB_VERSION = "THIRD_LIB_VERSION"


class Status(str, Enum):
    Fail = "Fail"
    Ready = "Ready"
    Running = "Running"
    Success = "Success"
    Timeout = "Timeout"
    Waiting = "Waiting"


class SymbolType(str, Enum):
    DATA_LABEL = "DATA_LABEL"
    FUNCTION = "FUNCTION"
    THUNK_FUNCTION = "THUNK_FUNCTION"


class XRefType(str, Enum):
    CALL = "CALL"
    DATA = "DATA"
    STRING = "STRING"
