# Generated by ariadne-codegen
# Source: ./src/binaryai/query.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class FileKHash(BaseModel):
    file: Optional["FileKHashFile"]


class FileKHashFile(BaseModel):
    decompile_result: Optional["FileKHashFileDecompileResult"] = Field(
        alias="decompileResult"
    )


class FileKHashFileDecompileResult(BaseModel):
    k_hash_info: Optional["FileKHashFileDecompileResultKHashInfo"] = Field(
        alias="kHashInfo"
    )


class FileKHashFileDecompileResultKHashInfo(BaseModel):
    hash: "FileKHashFileDecompileResultKHashInfoHash"


class FileKHashFileDecompileResultKHashInfoHash(BaseModel):
    hash: Any
    version: str


FileKHash.model_rebuild()
FileKHashFile.model_rebuild()
FileKHashFileDecompileResult.model_rebuild()
FileKHashFileDecompileResultKHashInfo.model_rebuild()
