# Generated by ariadne-codegen
# Source: ./src/binaryai/query.graphql

from typing import List, Optional

from .base_model import BaseModel


class Filename(BaseModel):
    file: Optional["FilenameFile"]


class FilenameFile(BaseModel):
    name: List[str]


Filename.model_rebuild()
