# Generated by ariadne-codegen on 2023-09-18 11:53
# Source: ./src/binaryai/query.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class MIMEType(BaseModel):
    file: Optional["MIMETypeFile"]


class MIMETypeFile(BaseModel):
    mime_type: str = Field(alias="mimeType")


MIMEType.model_rebuild()
MIMETypeFile.model_rebuild()
