# Generated by ariadne-codegen
# Source: ./src/binaryai/query.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class SCA(BaseModel):
    file: Optional["SCAFile"]


class SCAFile(BaseModel):
    scainfo: Optional[List["SCAFileScainfo"]]


class SCAFileScainfo(BaseModel):
    name: str
    version: Optional[str]
    description: Optional[str]
    source_code_url: Optional[str] = Field(alias="sourceCodeURL")
    summary: Optional[str]


SCA.model_rebuild()
SCAFile.model_rebuild()
