# Generated by ariadne-codegen on 2023-09-18 11:53
# Source: ./src/binaryai/query.graphql

from typing import Optional

from .base_model import BaseModel


class Sha256(BaseModel):
    file: Optional["Sha256File"]


class Sha256File(BaseModel):
    sha256: str


Sha256.model_rebuild()
Sha256File.model_rebuild()
